cidr_networks:
  container: 172.29.236.0/24
  tunnel: 192.168.90.0/24

used_ips:
  - "172.29.236.1,172.29.236.200"
  - "172.29.236.250,172.29.236.254"
  - "192.168.90.1,192.168.90.200"

global_overrides:
  internal_lb_vip_address: 192.168.90.190
  external_lb_vip_address: 172.29.236.190
  tunnel_bridge: "br-vxlan"
  management_bridge: "br-mgmt"
  provider_networks:
    - network:
        container_bridge: "br-mgmt"
        container_type: "veth"
        container_interface: "eth1"
        ip_from_q: "container"
        type: "raw"
        group_binds:
          - all_containers
          - hosts
        is_container_address: true
        is_ssh_address: true
    - network:
        container_bridge: "br-vxlan"
        container_type: "veth"
        container_interface: "eth10"
        ip_from_q: "tunnel"
        type: "vxlan"
        range: "1:1000"
        net_name: "vxlan"
        group_binds:
          - neutron_openvswitch_agent
    - network:
        container_bridge: "br-vlan"
        container_type: "veth"
        container_interface: "eth12"
        host_bind_override: "eth12"
        type: "flat"
        net_name: "flat"
        group_binds:
          - neutron_openvswitch_agent
    - network:
        container_bridge: "br-vlan"
        container_type: "veth"
        container_interface: "eth11"
        type: "vlan"
        range: "50:70"
        net_name: "physnet1"
        group_binds:
          - neutron_openvswitch_agent

###
### Infrastructure
###

# galera, memcache, rabbitmq, utility
shared-infra_hosts:
  osad-controller01s1:
    ip: 172.29.236.190

# repository (apt cache, python packages, etc)
repo-infra_hosts:
  osad-controller01s1:
    ip: 172.29.236.190

# load balancer
haproxy_hosts:
  osad-controller01s1:
    ip: 172.29.236.190

###
### OpenStack
###

# keystone
identity_hosts:
  osad-controller01s1:
    ip: 172.29.236.190

# cinder api services
storage-infra_hosts:
  osad-controller01s1:
    ip: 172.29.236.190

# glance
image_hosts:
  osad-controller01s1:
    ip: 172.29.236.190

# nova api, conductor, etc services
compute-infra_hosts:
  osad-controller01s1:
    ip: 172.29.236.190

# heat
orchestration_hosts:
  osad-controller01s1:
    ip: 172.29.236.190

# horizon
dashboard_hosts:
  osad-controller01s1:
    ip: 172.29.236.190

# neutron server, agents (L3, etc)
network_hosts:
  osad-controller01s1:
    ip: 172.29.236.190

# nova hypervisors
compute_hosts:
  osad-compute01s1:
    ip: 172.29.236.191
